#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
displayautoselect
setbg &			# set the background with the `setbg` script
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
wal -R --theme dracula -o ${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun
picom --config ${XDG_CONFIG_HOME:-$HOME/.config}/picom/picom.conf &

xdotool key super+F5

#autostart="mpd xcompmgr dunst unclutter pipewire remapd"
# autostart="dunst unclutter pipewire wireplumber remapd"
autostart="dunst unclutter remapd pipewire"

setxkbmap -option 'grp:alts_toggle' -layout 'us,ir' -variant ,,

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
